"""empty message

Revision ID: 066001e5e4f6
Revises: 27faf9830a36
Create Date: 2020-01-28 05:17:42.823272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '066001e5e4f6'
down_revision = '27faf9830a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('action_user_id', sa.Integer(), nullable=False))
    op.add_column('notification', sa.Column('information_text', sa.Text(), nullable=True))
    op.add_column('notification', sa.Column('receiver_user_id', sa.Integer(), nullable=False))
    op.drop_constraint('notification_ibfk_1', 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'users', ['action_user_id'], ['id'])
    op.create_foreign_key(None, 'notification', 'users', ['receiver_user_id'], ['id'])
    op.drop_column('notification', 'information')
    op.drop_column('notification', 'receiver_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('receiver_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('notification', sa.Column('information', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key('notification_ibfk_1', 'notification', 'users', ['receiver_id'], ['id'])
    op.drop_column('notification', 'receiver_user_id')
    op.drop_column('notification', 'information_text')
    op.drop_column('notification', 'action_user_id')
    # ### end Alembic commands ###
