"""empty message

Revision ID: 27faf9830a36
Revises: 079b94d21599
Create Date: 2020-01-27 21:27:41.376412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27faf9830a36'
down_revision = '079b94d21599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celebrities', sa.Column('avatar_url_last', sa.String(length=128), nullable=False))
    op.drop_column('celebrities', 'avatar_url')
    op.add_column('movies', sa.Column('image_url_last', sa.String(length=128), nullable=False))
    op.drop_column('movies', 'image_url')
    op.add_column('users', sa.Column('avatar_url_last', sa.String(length=128), nullable=True))
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', mysql.VARCHAR(collation='utf8mb4_bin', length=128), nullable=True))
    op.drop_column('users', 'avatar_url_last')
    op.add_column('movies', sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_bin', length=128), nullable=True))
    op.drop_column('movies', 'image_url_last')
    op.add_column('celebrities', sa.Column('avatar_url', mysql.VARCHAR(collation='utf8mb4_bin', length=128), nullable=True))
    op.drop_column('celebrities', 'avatar_url_last')
    # ### end Alembic commands ###
