"""empty message

Revision ID: 39d1878fedad
Revises: e061d6786663
Create Date: 2020-02-19 18:41:31.862518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "39d1878fedad"
down_revision = "e061d6786663"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("celebrities", "ext")
    op.drop_column("genres", "ext")
    op.drop_column("movies", "ext")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "movies",
        sa.Column(
            "ext", mysql.VARCHAR(collation="utf8mb4_bin", length=32), nullable=True
        ),
    )
    op.add_column(
        "genres",
        sa.Column(
            "ext", mysql.VARCHAR(collation="utf8mb4_bin", length=32), nullable=True
        ),
    )
    op.add_column(
        "celebrities",
        sa.Column(
            "ext", mysql.VARCHAR(collation="utf8mb4_bin", length=32), nullable=True
        ),
    )
    # ### end Alembic commands ###
