"""empty message

Revision ID: 74758dbad9cb
Revises: 5bce075aed29
Create Date: 2020-02-18 03:02:39.272075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "74758dbad9cb"
down_revision = "5bce075aed29"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("name", table_name="images")
    op.drop_table("images")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("created_at", mysql.DATETIME(), nullable=True),
        sa.Column("updated_at", mysql.DATETIME(), nullable=True),
        sa.Column(
            "name", mysql.VARCHAR(collation="utf8mb4_bin", length=20), nullable=True
        ),
        sa.Column("image", sa.BLOB(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_bin",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("name", "images", ["name"], unique=True)
    # ### end Alembic commands ###
