"""empty message

Revision ID: 7f0e818dc8ba
Revises: 066001e5e4f6
Create Date: 2020-01-28 05:45:46.529592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f0e818dc8ba'
down_revision = '066001e5e4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celebrities', sa.Column('aka_en_list', sa.Text(), nullable=True))
    op.add_column('celebrities', sa.Column('aka_list', sa.Text(), nullable=True))
    op.drop_column('celebrities', 'aka_text')
    op.drop_column('celebrities', 'aka_en_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celebrities', sa.Column('aka_en_text', mysql.TEXT(collation='utf8mb4_bin'), nullable=True))
    op.add_column('celebrities', sa.Column('aka_text', mysql.TEXT(collation='utf8mb4_bin'), nullable=True))
    op.drop_column('celebrities', 'aka_list')
    op.drop_column('celebrities', 'aka_en_list')
    # ### end Alembic commands ###
