"""empty message

Revision ID: e061d6786663
Revises: 6408fe1c220d
Create Date: 2020-02-19 11:44:48.836278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e061d6786663"
down_revision = "6408fe1c220d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("celebrities", sa.Column("ext", sa.String(length=32), nullable=True))
    op.add_column("genres", sa.Column("ext", sa.String(length=32), nullable=True))
    op.add_column("movies", sa.Column("ext", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movies", "ext")
    op.drop_column("genres", "ext")
    op.drop_column("celebrities", "ext")
    # ### end Alembic commands ###
