"""empty message

Revision ID: f813fc16fa16
Revises: 6400ca70539d
Create Date: 2020-02-12 21:31:39.786561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f813fc16fa16"
down_revision = "6400ca70539d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("followers_ibfk_1", "followers", type_="foreignkey")
    op.create_foreign_key(None, "followers", "users", ["followed_id"], ["id"])
    op.drop_constraint("user_roles_ibfk_1", "user_roles", type_="foreignkey")
    op.drop_constraint("user_roles_ibfk_2", "user_roles", type_="foreignkey")
    op.create_foreign_key(
        None, "user_roles", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "user_roles", "roles", ["role_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_roles", type_="foreignkey")
    op.drop_constraint(None, "user_roles", type_="foreignkey")
    op.create_foreign_key(
        "user_roles_ibfk_2", "user_roles", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "user_roles_ibfk_1", "user_roles", "roles", ["role_id"], ["id"]
    )
    op.drop_constraint(None, "followers", type_="foreignkey")
    op.create_foreign_key(
        "followers_ibfk_1", "followers", "roles", ["followed_id"], ["id"]
    )
    # ### end Alembic commands ###
